format = """
[ ](#a3aed2)\
$os$cmd_duration\
[ ](fg:#a3aed2 bg:#021631)\
$directory\
[ ](fg:#021631 bg:#03214a)\
$git_branch\
[ ](fg:#03214a bg:#042c62)\
$git_status\
[ ](fg:#042c62 bg:#05377b)\
$git_metrics\
[](fg:#05377b)\
\n$character\
"""

[os]
format = "[$symbol]($style)"
style = 'fg:#394260 bg:#a3aed2'
disabled = false

[os.symbols]
Macos = " "
Ubuntu = " "
Debian = " "
Linux = " "
NixOS = " "
Arch = " "
Windows = "󰍲 "

[cmd_duration]
min_time = 1
style = 'fg:#394260 bg:#a3aed2'
format = "[$duration]($style)"

[directory]
truncation_length = 6
truncation_symbol = '  '
truncate_to_repo = false
home_symbol = '  ~'
style = 'fg:#00aaaa bg:#021631'
read_only = '󰌾  '
read_only_style = 'fg:#f7768e bg:#021631'
format = '[ $path ]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = ' '
style = 'fg:#00aaaa bg:#03214a'
format = '[$symbol $branch(:$remote_branch) ]($style)'

[git_status]
style = 'fg:#00aaaa bg:#042c62'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = 's'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\] ]($style))'

[git_metrics]
added_style = 'fg:#00aaaa bg:#05377b'
deleted_style = 'fg:#00aaaa bg:#05377b'
format = '[+$added/-$deleted ]($deleted_style)'
disabled = false

[character]
success_symbol = '[ ❯](bold #00ffff)'
error_symbol = '[ ❯](bold red)'
